### ISSUE TITLE
Is there a demo.py for nuscenes dataset? 

### ISSUE THREAD

**Issue by EliomEssaim** [OpenPerceptionX/Openpilot-Deepdive#10]
I try to use the demo.py to visualize the result. but this file seems only compatible for comma2k19.

**Comment by ElectronicElephant** [comment]
Hi @EliomEssaim , 

For more info on dataloader for nuScenes, please refer to https://github.com/OpenPerceptionX/Openpilot-Deepdive/issues/9

thanks.
