### ISSUE TITLE
some questiones on nuscene

### ISSUE THREAD

**Issue by promesse** [OpenPerceptionX/Openpilot-Deepdive#16]
Thanks for your great work!
However i meet a problem when i train and demo for nuscene
I had already follow your issue(https://github.com/OpenPerceptionX/Openpilot-Deepdive/issues/9)
Maybe because i just train for 10epoch in nuscene mini batch, when i demo it, the prediction is all equal to 0
Have you ever meet it?
And i changed the ground truth to draw on the pic, the direction also seem not right
Car was clearly going to the left
![image](https://user-images.githubusercontent.com/26239060/205631674-f9e24f2a-6040-49bb-87e4-ff427a28cc8b.png)

**Comment by promesse** [comment]
meanwhile when you use gru to predict the 10 waypoints, why not use grucell to predict one by one?
does it make sense?
 
![image](https://user-images.githubusercontent.com/26239060/205646562-2348d1ac-aad1-4cf8-ad71-eb564a752c21.png)

**Comment by ElectronicElephant** [comment]
> And i changed the ground truth to draw on the pic, the direction also seem not right
> Car was clearly going to the left

You should double check your coordinate system. It's the fundamental requirement before you do anything in the real world.

**Comment by promesse** [comment]
?????? I use your demo code and find it

**Comment by promesse** [comment]
why you close it?

**Comment by promesse** [comment]
> > And i changed the ground truth to draw on the pic, the direction also seem not right
> > Car was clearly going to the left
> 
> You should double check your coordinate system. It's the fundamental requirement before you do anything in the real world.

-_-''
