### ISSUE TITLE
Openpilot-Deployment repo link is missed

### ISSUE THREAD

**Issue by LangDaoAI** [OpenPerceptionX/Openpilot-Deepdive#17]
Hi Team,

Openpilot-Deployment repo link is missed, please confirm it , thanks!

**Comment by ilnehc** [comment]
Thank you for your reminder, please check the updated version.

**Comment by gi123j** [comment]
I don't find the Openpilot-Deployment repo link in the deployment branch，Could you provide it again?
@ilnehc
