### ISSUE TITLE
[Question] About datasets annotation tool

### ISSUE THREAD

**Issue by LangDaoAI** [OpenPerceptionX/Openpilot-Deepdive#18]
Hi Team,

I want to ask which annotation tool you or openpilot team use for annotating public/private datasets.

Could you give me some suggestions?

Thanks!

**Comment by ElectronicElephant** [comment]
Hi,

We do not manually annotate the datasets used in our project. The position and trajectories are directly extracted from the GPS, which is provided in the dataset.

**Comment by LangDaoAI** [comment]
> Hi,
> 
> We do not manually annotate the datasets used in our project. The position and trajectories are directly extracted from the GPS, which is provided in the dataset.

Thanks your reply!
Then,  another question is : if needing to manually annotate the position and trajectories from a new dataset , has a good tool for annotating the position and trajectories ?

Thanks!
