### ISSUE TITLE
About dataset processing

### ISSUE THREAD

**Issue by L-Net-1992** [OpenPerceptionX/Openpilot-Deepdive#2]
Is there a detailed description or readme for data set processing? thank you

**Comment by ElectronicElephant** [comment]
Hi,

You can create a folder named `data`, and simply create soft links of the datasets. The folder structure should look like this

```
Openpilot-Deepdive 
├── tools
├── utils_comma2k19
├── data
      ├── nuscenes  -> soft link to the nusSenes-all dataset
      ├── comma2k19 -> soft link to the Comma2k19 dataset
```

Then, you can run the scripts in the `tools` folder to generate train/test splits. e.g., 
```
python tools/extract_comma2k19.py
```

No further processing is required. The random splits do not have a significant impact on results, so you can generate your own. We will also upload the splits we used later.

Thanks.

**Comment by L-Net-1992** [comment]
Do I need to download datasets in advance?

**Comment by ElectronicElephant** [comment]
Hi @L-Net-1992 

Yes, exactly.

**Comment by L-Net-1992** [comment]
Thank you. I will close this question.
