### ISSUE TITLE
Question about the experiment

### ISSUE THREAD

**Issue by YilinGao-SHU** [OpenPerceptionX/Openpilot-Deepdive#20]
Greetings, thanks for your reproduction of Openpilot, which has greatly advanced the work of freelance scholars in this field. Also, your experimental results have once again validated that Great Truths Are All Simple. I noticed in the experiments that you fine-tuned the SuperCombo model based on your pipeline and achieved better results than the baseline on the NuScense dataset (AP@2 0.809 vs. 0.692), but as far as I know SuperCombo is not open source, I would like to know if fine-tuning here refers to the OP- Deepdive trained on Comma2k19 and fine-tuned on NuScense dataset?
![image](https://user-images.githubusercontent.com/98305137/211717486-14c6ebff-f2df-4cf9-bb01-7d1fe9fdfb37.png)

**Comment by ElectronicElephant** [comment]
> SuperCombo is not open source

The trained model (a.k.a., the weights) of the SuperCombo is open-sourced, in ONNX format. However, the official training data and the training pipeline is not open-sourced. Therefore, we can simply load the ONNX model into PyTorch, and finetune it.

**Comment by YilinGao-SHU** [comment]
Thanks~ I will close this issue.
