### ISSUE TITLE
The trajectory predicted by the model tends to be a straight line

### ISSUE THREAD

**Issue by houwenbo87** [OpenPerceptionX/Openpilot-Deepdive#22]
During the training process using the comma2k19 dataset, the trajectory predicted by the model has always tended to be a straight line. Curved corners do not work well. 

Did you encounter this problem during training? How was it resolved? Can you provide your trained model and configuration?

**Comment by ElectronicElephant** [comment]
> Did you encounter this problem during training?

No.

> Can you provide your trained model and configuration?

We trained the model on 8 V100 GPUs for 100 epochs, as is described in the paper.

The model is trained on a cluster which is not connected to the internet. We are not allowed to download and share files from the cluster without approval.

**Comment by houwenbo87** [comment]
@ElectronicElephant Thank you very much for your reply!
