### ISSUE TITLE
About GRU training method.

### ISSUE THREAD

**Issue by EliomEssaim** [OpenPerceptionX/Openpilot-Deepdive#6]
I used to train GRU. Each sample data prepare a sequence of data.
However, the program train GRU by a sample with a sequence length of 1. And it backward for every 40 steps.
This seems to be equal to preparing a sample with a sequence length of 40. But actually, the program doesn't clear the variable named hidden, just detach it. This makes a difference in preparing a sample with a sequence of 40, as the latter clear variable named hidden into zero before computing.

https://github.com/OpenPerceptionX/Openpilot-Deepdive/blob/017d422f41216110043f9cda4d27658b7c3d92d9/main.py#L166

Could you tell me what's the purpose of applying such a training method in GRU？ That seems not to be explained well in paper. Thanks.

**Comment by ElectronicElephant** [comment]
Hi,

The reason why we don't clear the variable (reset it to zeros) is that in real world, openpilot keeps predicting and updating its hidden state. Therefore, it doesn't make sense if we reset it every 40 steps when training the network. I think it's common in RNNs, especially when you have very long sequences but limited GPU memory.

**Comment by EliomEssaim** [comment]
OK.Thanks.
