### ISSUE TITLE
About model deployment

### ISSUE THREAD

**Issue by L-Net-1992** [OpenPerceptionX/Openpilot-Deepdive#8]
About model deployment，Is there any relevant guidance on how to replace the official "plan" channel? Thank you.

**Comment by ilnehc** [comment]
We make the deployment repo public: https://github.com/OpenPerceptionX/Openpilot-Deployment. Currently, you probably need to explore it by yourself (prob. compared with the original Openpilot repo) since we are working on other projects. Please be patient for more instructions in it.

**Comment by L-Net-1992** [comment]
OK,TK.
