### ISSUE TITLE
get_dataloader for nuscenes dataset

### ISSUE THREAD

**Issue by didpurwanto** [OpenPerceptionX/Openpilot-Deepdive#9]
I see only comma2k19 exists in the ``get_dataloader`` for comma2k19 dataset in ``main.py``. Is there any updates for ``nuscense dataset``?
Thanks.

**Comment by ElectronicElephant** [comment]
Hi @didpurwanto ,

The current models do not give reasonable results on nuScenes dataset. We are still investigating this issue. Therefore, we recommend starting from comma2k19 dataset instead.

If you insist on using nuScenes dataset, you can either explore the early version of code (https://github.com/OpenPerceptionX/Openpilot-Deepdive/commit/b97f9d764d985da575182e4eaf64e9e1d5f987c1), or you can run the `[extract_nuscenes.py](https://github.com/OpenPerceptionX/Openpilot-Deepdive/blob/main/tools/extract_nuscenes.py)` script and use the `SequencePlanningDataset` class.

**Comment by didpurwanto** [comment]
Thanks for the confirmation. What do you think if we combine these two datasets into a single training option?

**Comment by ElectronicElephant** [comment]
Please note that the frame rate of these two datasets are different. Since "up-sample" the frame rate is no easy work, you have to down sample the frame rate of comma2k19 from 30Hz to 12 or 2 Hz. I'm afraid that it will negatively impact the perform.

**Comment by didpurwanto** [comment]
Yes, I have observed it and agree with you.
